### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by peerchemist**
added two cryptocoins to list of currrencies

### CODE REVIEW

**Review by PunitGr — APPROVED** [review]

**Comment by PunitGr** [comment]
Thank you for adding this :)

**Comment by PunitGr** [comment]
@peerchemist Forgot to add, can you also update the build and open another PR?
Auto deploy is not enabled right now for this repo.

**Comment by peerchemist** [comment]
I've tried compiling locally, it did not work. I can set up automated build system too, however you should first check out the build process and fix bugs.
I've used node v14.18.3 locally.

**Comment by peerchemist** [comment]
@PunitGr can you take a look, see what is wrong?

**Comment by PunitGr** [comment]
I'll have a look at it. :)

**Comment by PunitGr** [comment]
@peerchemist Sorry, for being so late on this. Your changes are live now.
For future I'll figure out a solution with gh-pages to have automatic deployment setup. 🙂

**Pull request merged**
